version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    image: ilopesjr/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    tty: true
    command: node index.js
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - node-network

networks:
  node-network:
    driver: bridge